### ISSUE TITLE
Eslint config file genrate error 

### ISSUE THREAD

**Issue by vfan** [eslint/create-config#102]
https://github.com/eslint/create-config/blob/dbd874289676e3b1442bf3d3984070b6fed5586b/lib/config-generator.js#L136

When my module is commonjs type,it generate eslint.config.mjs

**Comment by Rec0iL99** [comment]
Hi @vfan, I believe this is working as intended. By default, the generated ESLint config always follows `JavaScript modules` syntax (`import/export`). 

```js
import globals from "globals";
import pluginJs from "@eslint/js";


export default [
  {languageOptions: { globals: globals.node }},
  pluginJs.configs.recommended,
];
```

In your case since your project follows `commonjs` syntax (`require`), the config file will have the `.mjs` extension to indicate that this file must be evaluated using `JavaScript modules` syntax.
