### ISSUE TITLE
Consider offering eslint-plugin-node/eslint-plugin-n

### ISSUE THREAD

**Issue by segevfiner** [eslint/create-config#37]
Considering this repo itself and ESLint is using it, should we consider offering to add eslint-plugin-node? Should we offer any other commonly used plugins? e.g. Plugins that the ESLint project itself is using or that are common? Such as Jest, Prettier, etc.

**Comment by kecrily** [comment]
Considering that [`eslint-plugin-node` is no longer actively maintained](https://github.com/mysticatea/eslint-plugin-node/issues/300) and there is an active branch [`eslint-plugin-n]`(https://github.com/weiran-zsd/eslint-plugin-node), I think we should support `eslint-plugin-n` instead of `eslint-plugin-node` if we want to.

---

Also both ESLint and this repository could be considered for switching to `eslint-plugin-n`.

**Comment by MichaelDeBoey** [comment]
Let's hope we can transfer the original repo asap to the new @eslint-community org 🙏

See https://github.com/mysticatea/eslint-plugin-node/issues/341

**Comment by nzakas** [comment]
For now we aren't going to move forward with any changes.
